//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "direccion")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Binary(16)")]
    pub uuid: Vec<u8>,
    pub provincia: String,
    pub calle: String,
    pub altura: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ubicacion::Entity")]
    Ubicacion,
}

impl Related<super::ubicacion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ubicacion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
