//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::direccion::{Entity as DireccionEntity, Model as DireccionModel};
pub use super::heladera::{Entity as HeladeraEntity, Model as HeladeraModel};
pub use super::persona_vulnerable::{Entity as PersonaEntity, Model as PersonaModel};
pub use super::ubicacion::{Entity as UbicacionEntity, Model as UbicacionModel};
