//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::direccion::Entity as Direccion;
pub use super::persona_vulnerable::Entity as PersonaVulnerable;
pub use super::ubicacion::Entity as Ubicacion;
